In [2]:
# Importing libraries

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import ezodf

In [12]:
# Listing transaction datasets across 2020-2024

transaction_datasets = [
    '../data/raw/transactions_2020.csv',
    '../data/raw/transactions_2021.csv',
    '../data/raw/transactions_2022.csv',
    '../data/raw/transactions_2023.csv',
    '../data/raw/transactions_2024.csv',
]

In [15]:
# Defining column names for transaction datasets

transaction_columns = [
    'Transaction Unique Identifier',
    'Price',
    'Date of Transfer',
    'Postcode',
    'Property Type',
    'Old/New',
    'Duration',
    'PAON',
    'SAON',
    'Street',
    'Locality',
    'Town/City',
    'District',
    'County',
    'PPD Category Type',
    'Record Status'
]

In [ ]:
# Reading the property transaction datasets into a list

transaction_list = [pd.read_csv(dataset, header=None, names=transaction_columns) for dataset in transaction_datasets]

In [17]:
# Merging all datasets together into one dataframe

df_transactions = pd.concat(transaction_list, axis=0, ignore_index=True)

df_transactions

,Transaction Unique Identifier,Price,Date of Transfer,Postcode,Property Type,Old/New,Duration,PAON,SAON,Street,Locality,Town/City,District,County,PPD Category Type,Record Status
0,{AC07BBCF-E34C-0445-E053-6C04A8C01E31},150000,2020-06-12 00:00,WA7 5BU,D,N,F,12,NaN,ECCLESTON DRIVE,NaN,RUNCORN,HALTON,HALTON,A,A
1,{AC07BBCF-E34D-0445-E053-6C04A8C01E31},375000,2020-03-27 00:00,SK9 4ET,D,N,F,26,NaN,STANNEYLANDS DRIVE,NaN,WILMSLOW,CHESHIRE EAST,CHESHIRE EAST,A,A
2,{AC07BBCF-E34E-0445-E053-6C04A8C01E31},140000,2020-03-04 00:00,CW9 8BP,T,N,F,7,NaN,ADLINGTON DRIVE,NaN,NORTHWICH,CHESHIRE WEST AND CHESTER,CHESHIRE WEST AND CHESTER,A,A
3,{AC07BBCF-E34F-0445-E053-6C04A8C01E31},95000,2020-04-30 00:00,WA8 8UT,S,N,F,410,NaN,HALE ROAD,NaN,WIDNES,HALTON,HALTON,A,A
4,{AC07BBCF-E350-0445-E053-6C04A8C01E31},170000,2020-04-30 00:00,WA5 3LZ,S,N,F,2,NaN,CLARENCE AVENUE,GREAT SANKEY,WARRINGTON,WARRINGTON,WARRINGTON,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5022271,{1EAE3DF7-2F7E-9EB1-E063-4704A8C09D02},249500,2024-07-08 00:00,TA20 2QR,S,N,F,29,NaN,LINKHAY ORCHARD,SOUTH CHARD,CHARD,SOMERSET,SOMERSET,A,A
5022272,{1EAE3DF7-2F7F-9EB1-E063-4704A8C09D02},345000,2024-07-04 00:00,BA5 1UG,T,N,F,5,NaN,SOUTHOVER,NaN,WELLS,SOMERSET,SOMERSET,A,A
5022273,{1EAE3DF7-2F80-9EB1-E063-4704A8C09D02},165000,2024-07-01 00:00,TA18 8DA,F,N,L,CHRISTCHURCH COURT,FLAT 4,SOUTH STREET,NaN,CREWKERNE,SOMERSET,SOMERSET,A,A
5022274,{1EAE3DF7-2F81-9EB1-E063-4704A8C09D02},165000,2024-07-05 00:00,TA18 8ES,T,N,F,8,NaN,HERMITAGE STREET,NaN,CREWKERNE,SOMERSET,SOMERSET,A,A
5022275,{1EAE3DF7-2F82-9EB1-E063-4704A8C09D02},220000,2024-06-28 00:00,TA14 6PS,T,N,F,34,NaN,HIGH STREET,NaN,STOKE-SUB-HAMDON,SOMERSET,SOMERSET,A,A

In [ ]:
# Inspecting data types in df_transactions

df_transactions.dtypes

Transaction Unique Identifier    object
Price                             int64
Date of Transfer                 object
Postcode                         object
Property Type                    object
Old/New                          object
Duration                         object
PAON                             object
SAON                             object
Street                           object
Locality                         object
Town/City                        object
District                         object
County                           object
PPD Category Type                object
Record Status                    object
dtype: object

In [9]:
# Reading the Ofsted school inspection dataset and converting it into a Pandas DataFrame

sheet_schools = ezodf.opendoc('../data/raw/schools.ods').sheets[2] # Selecting the third sheet which contains the data

rows_schools = list(sheet_schools.rows())
headers_schools = [cell.value for cell in rows_schools[2]] # Obtaining column names from row index 2
records_schools = rows_schools[3:] # Obtaining data records from row index 3 onwards

data_schools = []
for record in records_schools:
    values = [cell.value for cell in record] # Extracting values to append into the list
    data_schools.append(values)

df_schools = pd.DataFrame(data_schools, columns=headers_schools) # Converting the list into a Pandas DataFrame

df_schools

,URN,Name,Five-Year Ofsted Inspection Data publish date,Publication type,Remit,As at date,Published date,Government office region,Local authority area,Constituency,...,Category of concern,Effectiveness of leadership and management,Quality of education,Personal development,Behaviour and attitudes,Safeguarding is effective?,Early years provision (where applicable),Sixth form provision (where applicable),Does the inspection relate to the URN of the current school?,None
0,100000.0,The Aldgate School,2025-04-02T00:00:00,OS,State-funded schools,2024-12-31T00:00:00,2024-07-11T00:00:00,London,City of London,Cities of London and Westminster,...,None,1.0,1.0,1.0,1.0,Yes,2.0,9.0,Yes,None
1,100005.0,Thomas Coram Centre,2025-04-02T00:00:00,OS,State-funded schools,2024-12-31T00:00:00,2014-07-02T00:00:00,London,Camden,Holborn and St Pancras,...,None,1.0,9.0,9.0,9.0,9.0,9.0,9.0,Yes,None
2,100006.0,Heath School,2025-04-02T00:00:00,OS,State-funded schools,2024-12-31T00:00:00,2024-07-04T00:00:00,London,Camden,Hampstead and Highgate,...,None,1.0,2.0,1.0,1.0,Yes,9.0,9.0,Yes,None
3,100007.0,Camden Primary Pupil Referral Unit,2025-04-02T00:00:00,OS,State-funded schools,2024-12-31T00:00:00,2015-05-05T00:00:00,London,Camden,Holborn and St Pancras,...,None,2.0,9.0,9.0,9.0,9.0,9.0,9.0,Yes,None
4,100008.0,Argyle Primary School,2025-04-02T00:00:00,OS,State-funded schools,2024-12-31T00:00:00,2022-11-17T00:00:00,London,Camden,Holborn and St Pancras,...,None,2.0,2.0,1.0,2.0,Yes,2.0,9.0,Yes,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131924,148026.0,"St Antony's Roman Catholic School, a Voluntary...",2024-12-03T00:00:00,OS,State-funded schools,2020-08-31T00:00:00,2019-11-28T00:00:00,North West,Trafford,Stretford and Urmston,...,SWK,4.0,3.0,2.0,2.0,Yes,9.0,9.0,No,None
131925,148036.0,Gloucester Academy,2024-12-03T00:00:00,OS,State-funded schools,2020-08-31T00:00:00,2018-05-29T00:00:00,South West,Gloucestershire,Gloucester,...,SM,4.0,9.0,9.0,9.0,No,9.0,3.0,No,None
131926,148039.0,Northbrook Primary Academy,2024-12-03T00:00:00,OS,State-funded schools,2020-08-31T00:00:00,2019-11-18T00:00:00,North West,Lancashire,South Ribble,...,SM,4.0,4.0,4.0,4.0,Yes,3.0,9.0,No,None
131927,148050.0,"St Monica's RC High School, a Voluntary Academy",2024-12-03T00:00:00,OS,State-funded schools,2020-08-31T00:00:00,2019-12-19T00:00:00,North West,Bury,Bury South,...,None,3.0,3.0,3.0,3.0,Yes,9.0,9.0,No,None
131928,NaN,None,None,None,None,None,None,None,None,None,...,None,NaN,NaN,NaN,NaN,None,NaN,NaN,None,None

In [24]:
# Inspecting data types in df_schools

df_schools.dtypes

URN                                                             float64
Name                                                             object
Five-Year Ofsted Inspection Data publish date                    object
Publication type                                                 object
Remit                                                            object
As at date                                                       object
Published date                                                   object
Government office region                                         object
Local authority area                                             object
Constituency                                                     object
Postcode                                                         object
Provider type                                                    object
Provision type                                                   object
Phase                                                            object
Deprivation band                                                 object
Overall effectiveness                                            object
Category of concern                                              object
Effectiveness of leadership and management                      float64
Quality of education                                            float64
Personal development                                            float64
Behaviour and attitudes                                         float64
Safeguarding is effective?                                       object
Early years provision (where applicable)                        float64
Sixth form provision (where applicable)                         float64
Does the inspection relate to the URN of the current school?     object
None                                                             object
dtype: object

In [10]:
# Reading the ONS Postcode Directory dataset

df_postcodes = pd.read_csv('../data/raw/postcodes.csv')

df_postcodes

,pcd7,pcd8,pcds,dointr,doterm,cty25cd,ced25cd,lad25cd,wd25cd,parncp25cd,...,lep21cd1,lep21cd2,pfa23cd,imd20ind,cal24cd,icb23cd,oa21cd,lsoa21cd,msoa21cd,ruc21ind
0,M1 1AA,M1 1AA,M1 1AA,199507,200904.0,E99999999,E99999999,E08000003,E05011376,E43000157,...,E37000015,NaN,E23000005,13409,E56000032,E54000057,E00180796,E01033651,E02006902,UN1
1,M1 1AD,M1 1AD,M1 1AD,200303,NaN,E99999999,E99999999,E08000003,E05011361,E43000157,...,E37000015,NaN,E23000005,12008,E56000032,E54000057,E00175827,E01033658,E02006902,UN1
2,M1 1AE,M1 1AE,M1 1AE,200501,NaN,E99999999,E99999999,E08000003,E05011376,E43000157,...,E37000015,NaN,E23000005,10952,E56000032,E54000057,E00176052,E01034129,E02006912,UN1
3,M1 1AF,M1 1AF,M1 1AF,200506,NaN,E99999999,E99999999,E08000003,E05011376,E43000157,...,E37000015,NaN,E23000005,8141,E56000032,E54000057,E00175961,E01033653,E02006912,UN1
4,M1 1AG,M1 1AG,M1 1AG,201003,202501.0,E99999999,E99999999,E08000003,E05011376,E43000157,...,E37000015,NaN,E23000005,10952,E56000032,E54000057,E00175823,E01034129,E02006912,UN1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59993,M99 1ZU,M99 1ZU,M99 1ZU,200701,NaN,E99999999,E99999999,E08000003,E05011376,E43000157,...,E37000015,NaN,E23000005,10952,E56000032,E54000057,E00175823,E01034129,E02006912,UN1
59994,M99 1ZW,M99 1ZW,M99 1ZW,200405,NaN,E99999999,E99999999,E08000003,E05011361,E43000157,...,E37000015,NaN,E23000005,12008,E56000032,E54000057,E00175827,E01033658,E02006902,UN1
59995,M99 2BE,M99 2BE,M99 2BE,200604,NaN,E99999999,E99999999,E08000003,E05011376,E43000157,...,E37000015,NaN,E23000005,10952,E56000032,E54000057,E00175823,E01034129,E02006912,UN1
59996,M99 2BS,M99 2BS,M99 2BS,200604,NaN,E99999999,E99999999,E08000003,E05011376,E43000157,...,E37000015,NaN,E23000005,10952,E56000032,E54000057,E00175823,E01034129,E02006912,UN1
59997,M99 2BT,M99 2BT,M99 2BT,200604,NaN,E99999999,E99999999,E08000003,E05011376,E43000157,...,E37000015,NaN,E23000005,10952,E56000032,E54000057,E00175823,E01034129,E02006912,UN1

In [25]:
# Inspecting data types in df_postcodes

df_postcodes.dtypes

pcd7           object
pcd8           object
pcds           object
dointr          int64
doterm        float64
cty25cd        object
ced25cd        object
lad25cd        object
wd25cd         object
parncp25cd     object
usrtypind       int64
east1m        float64
north1m       float64
gridind         int64
hlth19cd       object
nhser24cd      object
ctry25cd       object
rgn25cd        object
ssr95cd        object
pcon24cd       object
eer20cd        object
educ23cd       object
ttwa15cd       object
pco19cd        object
itl25cd        object
wdstl05cd      object
oa01cd         object
wdcas03cd      object
npark16cd      object
lsoa01cd       object
msoa01cd       object
ruc01ind       object
oac01ind       object
oa11cd         object
lsoa11cd       object
msoa11cd       object
wz11cd         object
sicbl24cd      object
bua24cd        object
ruc11ind       object
oac11ind       object
lat           float64
long          float64
lep21cd1       object
lep21cd2      float64
pfa23cd        object
imd20ind        int64
cal24cd        object
icb23cd        object
oa21cd         object
lsoa21cd       object
msoa21cd       object
ruc21ind       object
dtype: object

In [11]:
# Reading the IMD dataset

df_imd = pd.read_excel('../data/raw/imd.xlsx', sheet_name='IMD25')

df_imd

,LSOA code (2021),LSOA name (2021),Local Authority District code (2024),Local Authority District name (2024),Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOA
0,E01000001,City of London 001A,E09000001,City of London,26525,8
1,E01000002,City of London 001B,E09000001,City of London,31203,10
2,E01000003,City of London 001C,E09000001,City of London,25913,8
3,E01000005,City of London 001E,E09000001,City of London,14807,5
4,E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham,10917,4
...,...,...,...,...,...,...
33750,E01035758,Vale of White Horse 014H,E07000180,Vale of White Horse,27536,9
33751,E01035759,Vale of White Horse 015G,E07000180,Vale of White Horse,27902,9
33752,E01035760,Vale of White Horse 015H,E07000180,Vale of White Horse,27532,9
33753,E01035761,Vale of White Horse 015I,E07000180,Vale of White Horse,28981,9
33754,E01035762,West Oxfordshire 004H,E07000181,West Oxfordshire,24000,8

In [26]:
# Inspecting data types in df_transactions

df_imd.dtypes

LSOA code (2021)                                                                    object
LSOA name (2021)                                                                    object
Local Authority District code (2024)                                                object
Local Authority District name (2024)                                                object
Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived)                  int64
Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOA     int64
dtype: object